# Generated by Django 5.0.6 on 2024-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Enter new/old '),
        ),
    ]
