# Generated by Django 5.0.6 on 2024-07-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='pictures',
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='product_images/')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product_detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
