# Generated by Django 5.0.6 on 2024-07-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_detail_pictures_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='detail',
        ),
    ]
