# Generated by Django 5.0.6 on 2024-07-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_images_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='in_stock',
        ),
        migrations.CreateModel(
            name='Product_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='Product description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
