# Generated by Django 5.0.6 on 2024-07-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_all_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='product_images/')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_price', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorise_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='Accesorise description')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.accesorise')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorise_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25, verbose_name='Product color')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.accesorise')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorise_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.accesorise')),
            ],
        ),
        migrations.CreateModel(
            name='All_accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.accesorise')),
            ],
        ),
    ]
