# Generated by Django 5.0.6 on 2024-07-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_accesorise_accesorise_description_accesorise_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='product_images/')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_price', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=25)),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='Accessory description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accessory')),
            ],
        ),
    ]
