# Generated by Django 5.0.6 on 2024-07-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_accessory_accessoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='AccessoryImage',
        ),
    ]
