# Generated by Django 5.0.6 on 2024-07-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cookiegroup_cookie_logitem_cookie_main_natural_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.accesorise'),
        ),
    ]
