# Generated by Django 5.0.6 on 2024-07-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cart_accessory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accesorise',
            new_name='Accesorisse',
        ),
        migrations.RenameModel(
            old_name='All_accessories',
            new_name='Accessories',
        ),
        migrations.RemoveField(
            model_name='accesorise_detail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='accesorise_images',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='accessory',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.DeleteModel(
            name='Accesorise_description',
        ),
        migrations.DeleteModel(
            name='Accesorise_detail',
        ),
        migrations.DeleteModel(
            name='Accesorise_images',
        ),
    ]
