# Generated by Django 5.0.6 on 2024-07-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_accesorise_accesorisse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorisse',
        ),
    ]
