# Generated by Django 5.0.6 on 2024-07-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_oroduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oroduct',
        ),
    ]
