# Generated by Django 5.0.6 on 2024-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_oroduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='color_images/'),
        ),
    ]
