# Generated by Django 5.0.6 on 2024-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_detail_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('alt_text', models.CharField(max_length=255)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
            ],
        ),
    ]
