# Generated by Django 5.0.6 on 2024-07-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='side',
        ),
    ]
