# Generated by Django 5.0.6 on 2024-07-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_slide_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_url', models.URLField()),
            ],
        ),
    ]
