# Generated by Django 5.0.6 on 2024-07-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_all_products_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='show_on_all_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='show_on_index',
            field=models.BooleanField(default=False),
        ),
    ]
