# Generated by Django 5.0.6 on 2024-07-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_slide_show_on_all_products_slide_show_on_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_products',
            name='slide',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='show_on_all_products',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='show_on_index',
        ),
    ]
