# Generated by Django 5.0.6 on 2024-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_all_products_slide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
