# Generated by Django 5.0.6 on 2024-07-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_store_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
    